// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trijbstsrnveqpzrnmnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyaWpic3Rzcm52ZXFwenJubW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzk1MjgsImV4cCI6MjA2MjgxNTUyOH0.rp45zmFPYX3zs5pgiuiJtzK9wBJqhlrCU2MxroGDfK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);